v9.3要換成v9.10 (2021a)R2021a
glnxa64(linux版本)  要換成win64(windows版本)
# Download and install Matlab Compiler Runtime v9.10 (2021a)
#
# This docker file will configure an environment into which the Matlab compiler
# runtime will be installed and in which stand-alone matlab routines (such as
# those created with Matlab's deploytool) can be executed.
#
# See http://www.mathworks.com/products/compiler/mcr/ for more info.

FROM debian:stretch-slim

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -q update && \
    apt-get install -q -y --no-install-recommends \
	  xorg \
      unzip \
      wget \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    
# Install the MCR dependencies and some things we'll need and download the MCR
# from Mathworks -silently install it
RUN mkdir /mcr-install && \
    mkdir /opt/mcr && \
    cd /mcr-install && \
    wget -q http://ssd.mathworks.com/supportfiles/downloads/R2021a/deployment_files/R2021a/installers/glnxa64/MCR_R2021a_glnxa64_installer.zip && \
    unzip -q MCR_R2021a_win64_installer.zip && \
    rm -f MCR_R2021a_win64_installer.zip && \
    ./install -destinationFolder /opt/mcr -agreeToLicense yes -mode silent && \
    cd / && \
    rm -rf mcr-install

# Configure environment variables for MCR
ENV LD_LIBRARY_PATH /opt/mcr/v910/runtime/win64:/opt/mcr/v910/bin/win64:/opt/mcr/v910/sys/os/win64
ENV XAPPLRESDIR /opt/mcr/v910/X11/app-defaults